// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGvigWSyMtrztkP1kTWoiG7VqJFiUJTOM',
    appId: '1:511851975130:web:63acff19868202e24430e3',
    messagingSenderId: '511851975130',
    projectId: 'foodnote-4e3c3',
    authDomain: 'foodnote-4e3c3.firebaseapp.com',
    storageBucket: 'foodnote-4e3c3.appspot.com',
    measurementId: 'G-VZ0TTFL3RV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR2PpcNLxFH67p93Yc0hzSNyX9q8uRX4A',
    appId: '1:511851975130:android:553a925b9d066d6e4430e3',
    messagingSenderId: '511851975130',
    projectId: 'foodnote-4e3c3',
    storageBucket: 'foodnote-4e3c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7hY9xjCrxJcaPxv81VKBk3rs3ggTK808',
    appId: '1:511851975130:ios:098e7cb859477faa4430e3',
    messagingSenderId: '511851975130',
    projectId: 'foodnote-4e3c3',
    storageBucket: 'foodnote-4e3c3.appspot.com',
    iosClientId: '511851975130-07pbtqhan689glst4mlodpdmjlhff8gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7hY9xjCrxJcaPxv81VKBk3rs3ggTK808',
    appId: '1:511851975130:ios:376d5de583b268ca4430e3',
    messagingSenderId: '511851975130',
    projectId: 'foodnote-4e3c3',
    storageBucket: 'foodnote-4e3c3.appspot.com',
    iosClientId: '511851975130-tnisea1kirotgqtjibte7d1q3is7gqmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodnote.RunnerTests',
  );
}
